import type { SideNavItem } from "@/lib/types";
import Image from "next/image";

export const SIDENAV_ITEMS: SideNavItem[] = [
  {
    title: "Home",
    path: "/",
    icon: <Image src="/home.svg" height={25} width={25} alt="Home" />,
  },

  {
    title: "History",
    path: "/inbox",
    icon: <Image src="/wallet.svg" height={25} width={25} alt="Transactions" />,
  },
  {
    title: "Organizations",
    path: "/prepare",
    icon: (
      <Image
        src="/orgs.svg"
        height={25}
        width={25}
        alt="Read Articles to prepare for interviews"
      />
    ),
  },
  //   {
  //     title: "Projects",
  //     path: "/projects",
  //     icon: <Icon icon="lucide:folder" width="24" height="24" />,
  //     submenu: true,
  //     subMenuItems: [
  //       { title: "All", path: "/projects" },
  //       { title: "Web Design", path: "/projects/web-design" },
  //       { title: "Graphic Design", path: "/projects/graphic-design" },
  //     ],
  //   },
  //   {
  //     title: "Messages",
  //     path: "/messages",
  //     icon: <Icon icon="lucide:mail" width="24" height="24" />,
  //   },
  //   {
  //     title: "Settings",
  //     path: "/settings",
  //     icon: <Icon icon="lucide:settings" width="24" height="24" />,
  //     submenu: true,
  //     subMenuItems: [
  //       { title: "Account", path: "/settings/account" },
  //       { title: "Privacy", path: "/settings/privacy" },
  //     ],
  //   },
  //   {
  //     title: "Help",
  //     path: "/help",
  //     icon: <Icon icon="lucide:help-circle" width="24" height="24" />,
  //   },
];

export const LOCATION_ITEMS = [
  { name: "Afghanistan", code: "af", numericCode: "004" },
  { name: "Åland Islands", code: "ax", numericCode: "248" },
  { name: "Albania", code: "al", numericCode: "008" },
  { name: "Algeria", code: "dz", numericCode: "012" },
  { name: "American Samoa", code: "as", numericCode: "016" },
  { name: "AndorrA", code: "ad", numericCode: "020" },
  { name: "Angola", code: "ao", numericCode: "024" },
  { name: "Anguilla", code: "ai", numericCode: "660" },
  { name: "Antarctica", code: "aq", numericCode: "010" },
  { name: "Antigua and Barbuda", code: "ag", numericCode: "028" },
  { name: "Argentina", code: "ar", numericCode: "032" },
  { name: "Armenia", code: "am", numericCode: "051" },
  { name: "Aruba", code: "aw", numericCode: "533" },
  { name: "Australia", code: "au", numericCode: "036" },
  { name: "Austria", code: "at", numericCode: "040" },
  { name: "Azerbaijan", code: "az", numericCode: "031" },
  { name: "Bahamas", code: "bs", numericCode: "044" },
  { name: "Bahrain", code: "bh", numericCode: "048" },
  { name: "Bangladesh", code: "bd", numericCode: "050" },
  { name: "Barbados", code: "bb", numericCode: "052" },
  { name: "Belarus", code: "by", numericCode: "112" },
  { name: "Belgium", code: "be", numericCode: "056" },
  { name: "Belize", code: "bz", numericCode: "084" },
  { name: "Benin", code: "bj", numericCode: "204" },
  { name: "Bermuda", code: "bm", numericCode: "060" },
  { name: "Bhutan", code: "bt", numericCode: "064" },
  { name: "Bolivia", code: "bo", numericCode: "068" },
  { name: "Bosnia and Herzegovina", code: "ba", numericCode: "070" },
  { name: "Botswana", code: "bw", numericCode: "072" },
  { name: "Bouvet Island", code: "bv", numericCode: "074" },
  { name: "Brazil", code: "br", numericCode: "076" },
  {
    name: "British Indian Ocean Territory",
    code: "io",
    numericCode: "086",
  },
  { name: "Bulgaria", code: "bg", numericCode: "100" },
  { name: "Burkina Faso", code: "bf", numericCode: "854" },
  { name: "Burundi", code: "bi", numericCode: "108" },
  { name: "Cambodia", code: "kh", numericCode: "116" },
  { name: "Cameroon", code: "cm", numericCode: "120" },
  { name: "Canada", code: "ca", numericCode: "124" },
  { name: "Cape Verde", code: "cv", numericCode: "132" },
  { name: "Cayman Islands", code: "ky", numericCode: "136" },
  { name: "Central African Republic", code: "cf", numericCode: "140" },
  { name: "Chad", code: "td", numericCode: "148" },
  { name: "Chile", code: "cl", numericCode: "152" },
  { name: "China", code: "cn", numericCode: "156" },
  { name: "Christmas Island", code: "cx", numericCode: "162" },
  { name: "Cocos (Keeling) Islands", code: "cc", numericCode: "166" },
  { name: "Colombia", code: "co", numericCode: "170" },
  { name: "Comoros", code: "km", numericCode: "174" },
  { name: "Congo", code: "cg", numericCode: "178" },
  {
    name: "Congo, The Democratic Republic of the",
    code: "cd",
    numericCode: "180",
  },
  { name: "Cook Islands", code: "ck", numericCode: "184" },
  { name: "Costa Rica", code: "cr", numericCode: "188" },
  { name: "Cote D'Ivoire", code: "ci", numericCode: "384" },
  { name: "Croatia", code: "hr", numericCode: "191" },
  { name: "Cuba", code: "cu", numericCode: "192" },
  { name: "Cyprus", code: "cy", numericCode: "196" },
  { name: "Czech Republic", code: "cz", numericCode: "203" },
  { name: "Denmark", code: "dk", numericCode: "208" },
  { name: "Djibouti", code: "dj", numericCode: "262" },
  { name: "Dominica", code: "dm", numericCode: "212" },
  { name: "Dominican Republic", code: "do", numericCode: "214" },
  { name: "Ecuador", code: "ec", numericCode: "218" },
  { name: "Egypt", code: "eg", numericCode: "818" },
  { name: "El Salvador", code: "sv", numericCode: "222" },
  { name: "Equatorial Guinea", code: "gq", numericCode: "226" },
  { name: "Eritrea", code: "er", numericCode: "232" },
  { name: "Estonia", code: "ee", numericCode: "233" },
  { name: "Ethiopia", code: "et", numericCode: "231" },
  {
    name: "Falkland Islands (Malvinas)",
    code: "fk",
    numericCode: "238",
  },
  { name: "Faroe Islands", code: "fo", numericCode: "234" },
  { name: "Fiji", code: "fj", numericCode: "242" },
  { name: "Finland", code: "fi", numericCode: "246" },
  { name: "France", code: "fr", numericCode: "250" },
  { name: "French Guiana", code: "gf", numericCode: "254" },
  { name: "French Polynesia", code: "pf", numericCode: "258" },
  {
    name: "French Southern Territories",
    code: "tf",
    numericCode: "260",
  },
  { name: "Gabon", code: "ga", numericCode: "266" },
  { name: "Gambia", code: "gm", numericCode: "270" },
  { name: "Georgia", code: "ge", numericCode: "268" },
  { name: "Germany", code: "de", numericCode: "276" },
  { name: "Ghana", code: "gh", numericCode: "288" },
  { name: "Gibraltar", code: "gi", numericCode: "292" },
  { name: "Greece", code: "gr", numericCode: "300" },
  { name: "Greenland", code: "gl", numericCode: "304" },
  { name: "Grenada", code: "gd", numericCode: "308" },
  { name: "Guadeloupe", code: "gp", numericCode: "312" },
  { name: "Guam", code: "gu", numericCode: "316" },
  { name: "Guatemala", code: "gt", numericCode: "320" },
  { name: "Guernsey", code: "gg", numericCode: "831" },
  { name: "Guinea", code: "gn", numericCode: "324" },
  { name: "Guinea-Bissau", code: "gw", numericCode: "624" },
  { name: "Guyana", code: "gy", numericCode: "328" },
  { name: "Haiti", code: "ht", numericCode: "332" },
  { name: "Honduras", code: "hn", numericCode: "340" },
  { name: "Hong Kong", code: "hk", numericCode: "344" },
  { name: "Hungary", code: "hu", numericCode: "348" },
  { name: "Iceland", code: "is", numericCode: "352" },
  { name: "India", code: "in", numericCode: "356" },
  { name: "Indonesia", code: "id", numericCode: "360" },
  { name: "Iraq", code: "iq", numericCode: "368" },
  { name: "Ireland", code: "ie", numericCode: "372" },
  { name: "Israel", code: "il", numericCode: "376" },
  { name: "Italy", code: "it", numericCode: "380" },
  { name: "Jamaica", code: "jm", numericCode: "388" },
  { name: "Japan", code: "jp", numericCode: "392" },
  { name: "Jersey", code: "je", numericCode: "832" },
  { name: "Jordan", code: "jo", numericCode: "400" },
  { name: "Kazakhstan", code: "kz", numericCode: "398" },
  { name: "Kenya", code: "ke", numericCode: "404" },
  { name: "Kiribati", code: "ki", numericCode: "296" },
  { name: "Korea, Republic of", code: "kr", numericCode: "410" },
  { name: "Kuwait", code: "kw", numericCode: "414" },
  { name: "Kyrgyzstan", code: "kg", numericCode: "417" },
  { name: "Latvia", code: "lv", numericCode: "428" },
  { name: "Lebanon", code: "lb", numericCode: "422" },
  { name: "Lesotho", code: "ls", numericCode: "426" },
  { name: "Liberia", code: "lr", numericCode: "430" },
  { name: "Liechtenstein", code: "li", numericCode: "438" },
  { name: "Lithuania", code: "lt", numericCode: "440" },
  { name: "Luxembourg", code: "lu", numericCode: "442" },
  { name: "Macao", code: "mo", numericCode: "446" },
  { name: "Madagascar", code: "mg", numericCode: "450" },
  { name: "Malawi", code: "mw", numericCode: "454" },
  { name: "Malaysia", code: "my", numericCode: "458" },
  { name: "Maldives", code: "mv", numericCode: "462" },
  { name: "Mali", code: "ml", numericCode: "466" },
  { name: "Malta", code: "mt", numericCode: "470" },
  { name: "Marshall Islands", code: "mh", numericCode: "584" },
  { name: "Martinique", code: "mq", numericCode: "474" },
  { name: "Mauritania", code: "mr", numericCode: "478" },
  { name: "Mauritius", code: "mu", numericCode: "480" },
  { name: "Mayotte", code: "yt", numericCode: "175" },
  { name: "Mexico", code: "mx", numericCode: "484" },
  { name: "Monaco", code: "mc", numericCode: "492" },
  { name: "Mongolia", code: "mn", numericCode: "496" },
  { name: "Montserrat", code: "ms", numericCode: "500" },
  { name: "Morocco", code: "ma", numericCode: "504" },
  { name: "Mozambique", code: "mz", numericCode: "508" },
  { name: "Myanmar", code: "mm", numericCode: "104" },
  { name: "Namibia", code: "na", numericCode: "516" },
  { name: "Nauru", code: "nr", numericCode: "520" },
  { name: "Nepal", code: "np", numericCode: "524" },
  { name: "Netherlands", code: "nl", numericCode: "528" },
  { name: "New Caledonia", code: "nc", numericCode: "540" },
  { name: "New Zealand", code: "nz", numericCode: "554" },
  { name: "Nicaragua", code: "ni", numericCode: "558" },
  { name: "Niger", code: "ne", numericCode: "562" },
  { name: "Nigeria", code: "ng", numericCode: "566" },
  { name: "Niue", code: "nu", numericCode: "570" },
  { name: "Norfolk Island", code: "nf", numericCode: "574" },
  { name: "Northern Mariana Islands", code: "mp", numericCode: "580" },
  { name: "Norway", code: "no", numericCode: "578" },
  { name: "Oman", code: "om", numericCode: "512" },
  { name: "Pakistan", code: "pk", numericCode: "586" },
  { name: "Palau", code: "pw", numericCode: "585" },
  { name: "Panama", code: "pa", numericCode: "591" },
  { name: "Papua New Guinea", code: "pg", numericCode: "598" },
  { name: "Paraguay", code: "py", numericCode: "600" },
  { name: "Peru", code: "pe", numericCode: "604" },
  { name: "Philippines", code: "ph", numericCode: "608" },
  { name: "Pitcairn", code: "pn", numericCode: "612" },
  { name: "Poland", code: "pl", numericCode: "616" },
  { name: "Portugal", code: "pt", numericCode: "620" },
  { name: "Puerto Rico", code: "pr", numericCode: "630" },
  { name: "Qatar", code: "qa", numericCode: "634" },
  { name: "Reunion", code: "re", numericCode: "638" },
  { name: "Romania", code: "ro", numericCode: "642" },
  { name: "Russian Federation", code: "ru", numericCode: "643" },
  { name: "RWANDA", code: "rw", numericCode: "646" },
  { name: "Saint Helena", code: "sh", numericCode: "654" },
  {
    name: "Saint Kitts and Nevis",
    code: "kn",
    numericCode: "659",
  },
  { name: "Saint Lucia", code: "lc", numericCode: "662" },
  {
    name: "Saint Pierre and Miquelon",
    code: "pm",
    numericCode: "666",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "vc",
    numericCode: "670",
  },
  { name: "Samoa", code: "ws", numericCode: "882" },
  { name: "San Marino", code: "sm", numericCode: "674" },
  { name: "Sao Tome and Principe", code: "st", numericCode: "678" },
  { name: "Saudi Arabia", code: "sa", numericCode: "682" },
  { name: "Senegal", code: "sn", numericCode: "686" },
  { name: "Serbia and Montenegro", code: "cs", numericCode: "891" },
  { name: "Seychelles", code: "sc", numericCode: "690" },
  { name: "Sierra Leone", code: "sl", numericCode: "694" },
  { name: "Singapore", code: "sg", numericCode: "702" },
  { name: "Slovakia", code: "sk", numericCode: "703" },
  { name: "Slovenia", code: "si", numericCode: "705" },
  { name: "Solomon Islands", code: "sb", numericCode: "090" },
  { name: "Somalia", code: "so", numericCode: "706" },
  { name: "South Africa", code: "za", numericCode: "710" },
  { name: "Spain", code: "es", numericCode: "724" },
  { name: "Sri Lanka", code: "lk", numericCode: "144" },
  { name: "Sudan", code: "sd", numericCode: "729" },
  { name: "Suriname", code: "sr", numericCode: "740" },
  { name: "Svalbard and Jan Mayen", code: "sj", numericCode: "744" },
  { name: "Swaziland", code: "sz", numericCode: "748" },
  { name: "Sweden", code: "se", numericCode: "752" },
  { name: "Switzerland", code: "ch", numericCode: "756" },
  { name: "Taiwan, Province of China", code: "tw", numericCode: "158" },
  { name: "Tajikistan", code: "tj", numericCode: "762" },
  {
    name: "Tanzania, United Republic of",
    code: "tz",
    numericCode: "834",
  },
  { name: "Thailand", code: "th", numericCode: "764" },
  { name: "Timor-Leste", code: "tl", numericCode: "626" },
  { name: "Togo", code: "tg", numericCode: "768" },
  { name: "Tokelau", code: "tk", numericCode: "772" },
  { name: "Tonga", code: "to", numericCode: "776" },
  { name: "Trinidad and Tobago", code: "tt", numericCode: "780" },
  { name: "Tunisia", code: "tn", numericCode: "788" },
  { name: "Turkey", code: "tr", numericCode: "792" },
  { name: "Turkmenistan", code: "tm", numericCode: "795" },
  {
    name: "Turks and Caicos Islands",
    code: "tc",
    numericCode: "796",
  },
  { name: "Tuvalu", code: "tv", numericCode: "798" },
  { name: "Uganda", code: "ug", numericCode: "800" },
  { name: "Ukraine", code: "ua", numericCode: "804" },
  { name: "United Arab Emirates", code: "ae", numericCode: "784" },
  { name: "United Kingdom", code: "gb", numericCode: "826" },
  { name: "United States", code: "us", numericCode: "840" },
  { name: "Uruguay", code: "uy", numericCode: "858" },
  { name: "Uzbekistan", code: "uz", numericCode: "860" },
  { name: "Vanuatu", code: "vu", numericCode: "548" },
  { name: "Venezuela", code: "ve", numericCode: "862" },
  { name: "Viet Nam", code: "vn", numericCode: "704" },
  {
    name: "Virgin Islands, British",
    code: "vg",
    numericCode: "092",
  },
  { name: "Virgin Islands, U.S.", code: "vi", numericCode: "850" },
  { name: "Wallis and Futuna", code: "wf", numericCode: "876" },
  { name: "Western Sahara", code: "eh", numericCode: "732" },
  { name: "Yemen", code: "ye", numericCode: "887" },
  { name: "Zambia", code: "zm", numericCode: "894" },
  { name: "Zimbabwe", code: "zw", numericCode: "716" },
];
